# Generated by Django 4.0.2 on 2022-02-12 07:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("price_paid", models.IntegerField(help_text="Price paid [£]")),
                (
                    "transaction_date",
                    models.DateField(help_text="Date of transaction"),
                ),
                (
                    "postcode",
                    models.CharField(help_text="Postal code", max_length=8),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("D", "detached"),
                            ("S", "semi-detached"),
                            ("T", "terraced"),
                            ("F", "flat-maisonette"),
                            ("O", "other"),
                        ],
                        help_text="Type of property",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
